# CI CD for starter theme
name: CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 12
          cache: 'npm'

      - name: Install Node Modules
        run: npm i

      - name: Build App
        run: npm run prod

      - name: Log files
        run: ls -a    